### ISSUE TITLE
Ghost Monitors: Navigating Invisible Screens in Sway on Regolith

### ISSUE THREAD

**Issue by rmasad** [regolith-linux/sway-regolith#13]
**Sway Version:**
1.8

**Description:**
When using Regolith with Sway on a notebook, I encounter the following issue: After turning on the notebook, connecting it to two external monitors, and then closing the notebook's lid, the third monitor (the notebook's own screen) remains active despite not appearing in the Gnome settings monitor list. This situation prevents actions such as using the <Super> + Left shortcut to move to the left monitor.

**Comment by SoumyaRanjanPatnaik** [comment]
Weird. Can you check if you have `regolith-sway-clamshell` installed?

**Comment by SoumyaRanjanPatnaik** [comment]
Also share the output for `swaymsg -t get_outputs`

**Comment by rmasad** [comment]
`regolith-sway-clamshell` was not installed, I installed it and rebooted. It still doesn't work.

I attach a screenshot of the command (`swaymsg -t get_outputs`) and the Gnome configuration where the discrepancy is seen.

![image](https://github.com/regolith-linux/sway-regolith/assets/49078/fb070b46-d80c-4594-bfd3-c78f733b8030)

**Comment by SoumyaRanjanPatnaik** [comment]
With your notebook's lid open, can you try the following command:
```
swaymsg output eDP-1 disable
```

Does this turn off your display? Do you still see the same behaviour (ghost monitors as you say)?

**Comment by rmasad** [comment]
It works. When I run `swaymsg output eDP-1 disable`, the behavior you expect when the lid is closed happens.

How can I make this behavior automatic?

**Comment by SoumyaRanjanPatnaik** [comment]
Try executing `regolith-sway-clamshell` and see if you get the expected lid close behaviour.

**Comment by rmasad** [comment]
It works. There is a no-tricky way to enable in start-up?

**Comment by rmasad** [comment]
Another thing, when I reload regolith, I have to run regolith-sway-clamshell again

**Comment by fhchl** [comment]
Observing the exact same behavior.

**Comment by SoumyaRanjanPatnaik** [comment]
> It works. There is a no-tricky way to enable in start-up?

It does [execute on startup](https://github.com/regolith-linux/regolith-wm-config/blob/main/usr/share/regolith/sway/config.d/96_clamshell). Can you check if the config to launch clamshell at startup is installed at `/usr/share/regolith/sway/config.d/96_clamshell`?

**Comment by SoumyaRanjanPatnaik** [comment]
> Try executing regolith-sway-clamshell and see if you get the expected lid close 

@fhchl can you verify if this is the case for you as well.

**Comment by rmasad** [comment]
> > It works. There is a no-tricky way to enable in start-up?
> 
> It does [execute on startup](https://github.com/regolith-linux/regolith-wm-config/blob/main/usr/share/regolith/sway/config.d/96_clamshell). Can you check if the config to launch clamshell at startup is installed at `/usr/share/regolith/sway/config.d/96_clamshell`?

```
cat /usr/share/regolith/sway/config.d/96_clamshell
# Resource name to override the builtin display connector: wm.clamshell.display
# Resource name to override the lid close action: wm.clamshell.action
exec_always regolith-sway-clamshell
```

**Comment by fhchl** [comment]
> @fhchl can you verify if this is the case for you as well.

Yes, as I meant to say: it behaves _exactly_ the same way. 😄 Also the content of `/usr/share/regolith/sway/config.d/96_clamshell` is the same.
