### ISSUE TITLE
Touchpad Scrolling Not Working in Sway's Tabbed/Stacked Mode

### ISSUE THREAD

**Issue by rmasad** [regolith-linux/sway-regolith#14]
Hello Regolith Team,

I've encountered an issue while using Regolith with the Sway window manager, specifically when windows are in tabbed or stacked mode. The problem is that scrolling through the windows (to change the active one) with the touchpad does not work, whereas using a mouse's scroll wheel functions as expected.

**Environment:**
- Regolith Version: 3.1
- Sway Version: 1.8
- Operating System: Ubuntu 

**Steps to Reproduce:**
1. Open multiple windows in Sway under Regolith.
2. Change the window layout to either tabbed or stacked mode.
3. Attempt to scroll within a window title using the touchpad.

**Expected Behavior:**
Scrolling with the touchpad should allow me to change the active window, how it works when using a mouse.

**Actual Behavior:**
Scrolling with the touchpad has no change in which the active window is, while mouse scrolling works perfectly.

Thank you for your time and effort in maintaining Regolith and Regolith Sway.

**Comment by SoumyaRanjanPatnaik** [comment]
I can confirm this behaviour. Does i3 allow scrolling on the window title to change tabs? If it does, you can file an issue with the upstream sway repo [here](https://github.com/swaywm/sway/issues) with the `i3-compat` tag.
