### ISSUE TITLE
Cannot Install Dunst on Regolith 3 with Sway due to Dependency Conflicts with Regolith-rofication in Ubuntu 22.04

### ISSUE THREAD

**Issue by rmasad** [regolith-linux/sway-regolith#9]
**Environment**:

- Operating System: Ubuntu 22.04
- Regolith Version: 3.0
- Sway Version: 1.7
- Dunst Version: 1.5.0 (Attempted to Install)
- Regolith-rofication Version: 1.5.0 (Installed)

**Description**:
I encountered an issue while attempting to install Dunst for notifications on a Regolith 3 environment with the Sway window manager in Ubuntu 22.04. The installation fails due to dependency conflicts with regolith-rofication, preventing users from using Dunst as their preferred notification service.

**Steps to Reproduce**:

1. Install Ubuntu 22.04.
2. Install and set up Regolith 3 to use the Sway window manager.
3. Attempt to install Dunst using sudo apt install dunst.
4. Observe that the installation fails and reports dependency conflicts with regolith-rofication.

**Comment by mpareja** [comment]
@rmasad Have you tried disabling rofication when installing? I'm not using sway, but here's my install command line:

```bash
sudo apt install regolith-desktop regolith-session-flashback regolith-rofication-
```

Notice the trailing minus sign after `regolith-rofication`.

**Comment by rmasad** [comment]
`regolith-wm-rofication-ilia` depends on `regolith-rofication`, and `regolith-sway-root-config` depends on `regolith-wm-rofication-ilia`.

**Comment by mpareja** [comment]
Okay, cool, `regolith-sway-root-config` depending on `regolith-wm-rofication-ilia` sounds like a bug.

**Comment by davewongillies** [comment]
Probably is related to this https://github.com/regolith-linux/regolith-wm-config/pull/10

**Comment by mpareja** [comment]
From what I can tell, this is still an issue. It's a blocker to my adoption of Sway for Regolith.

**Comment by mpareja** [comment]
I believe this issue can be closed. I had no issue installing sway without rofication:

```bash
sudo apt install regolith-desktop regolith-session-sway regolith-look-nord regolith-rofication-
```

Can you confirm @rmasad?

**Comment by rmasad** [comment]
regolith-wm-rofication-ilia still depends of regolith-rofication and regolith-sway-root-config depends of regolith-wm-rofication-ilia

**Comment by mpareja** [comment]
Maybe this is still a problem on the 22.04 repositories? I'm on Ubuntu Mantic and it looks good here.

Only a few packages depend on `regolith-wm-rofication-ilia`. And the rofi-agnostic ones (the bottom three below) all have it listed as _recommended_ rather than required.

```bash
$ apt-cache rdepends regolith-wm-rofication-ilia
regolith-wm-rofication-ilia
Reverse Depends:
  regolith-i3-rofication
  regolith-wm-config
  regolith-session-sway
  regolith-session-flashback
```
![2024-02-19_14-38](https://github.com/regolith-linux/sway-regolith/assets/121724/51b2c0b2-5a93-4d6e-b008-ce1bae02bb8f)

**Comment by rmasad** [comment]
I just upgraded to Ubuntu 23.10 and it still needs the same dependency

**Comment by rmasad** [comment]
I needed to update the repositories. Now it was installed without uninstalling dnust.
